import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

import java.util.Map;
// https://www.baeldung.com/aws-lambda-api-gateway
// mvn clean package shade:shade
public class LambdaInvokeSource implements RequestHandler<Map<String,Object>, String> {
    public String handleRequest(Map<String,Object> input, Context context) {
        String returnString="";
        System.out.println(input.toString());

        if(input.toString().contains("aws.events")) {
            System.out.println("The event was generated by Cloudwatch Event");
            returnString = "The event was generated by Cloudwatch Event";
        }
        else if(input.toString().contains(".execute-api.")) {
            System.out.println("The event was generated by Api Gateway");
            returnString = "The event was generated by Api Gateway";
        }
        else {
            System.out.println("Event from unknown source");
            returnString = "Event from unknown source";
        }
        return returnString;
    }
}

//my hander: LambdaInvokeSource::handleRequest
//arn:aws:lambda:ap-southeast-2:251508406573:function:event-type-java